### ISSUE TITLE
Spacy 3 is not supported

### ISSUE THREAD

**Issue by janwendt** [Liebeck/spacy-sentiws#3]
Spacy 3 is not supported: https://spacy.io/usage/v3#migrating-add-pipe
When trying to execute i get this exception:
```
>>> nlp = spacy.load("de_core_news_md")
>>> sentiws = spaCySentiWS(sentiws_path="...")
>>> nlp.add_pipe(sentiws)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\...\.conda\envs\jw\lib\site-packages\spacy\language.py", line 754, in add_pipe
    raise ValueError(err)
ValueError: [E966] `nlp.add_pipe` now takes the string name of the registered component factory, not a callable component. Expected string, but got <spacy_sentiws.spaCySentiWS object at 0x000001DD854C0B20> (name: 'None').

- If you created your component with `nlp.create_pipe('name')`: remove nlp.create_pipe and call `nlp.add_pipe('name')` instead.

- If you passed in a component like `TextCategorizer()`: call `nlp.add_pipe` with the string name instead, e.g. `nlp.add_pipe('textcat')`.

- If you're using a custom component: Add the decorator `@Language.component` (for function components) or `@Language.factory` (for class components / factories) to your custom component and assign it a name, e.g. `@Language.component('your_name')`. You can then run `nlp.add_pipe('your_name')` to add it to the pipeline.
```

**Comment by fogx** [comment]
it seems this was fixed in #4, but i can't get it to work regardless.

> [E002] Can't find factory for 'sentiws' for language German (de).

```
nlp = spacy.load('de_core_news_md')
nlp.add_pipe('sentiws', config={'sentiws_path': 'data/sentiws/'})
doc = nlp('Die Dummheit der Unterwerfung blüht in hübschen Farben.')

for token in doc:
    print('{}, {}, {}'.format(token.text, token._.sentiws, token.pos_))
```
The pypi dir shows the last update in 2019, which may be the issue here?
